export const skillRecipes = [
  {
    id: 1,
    title: "Perfect Pastries",
    category: "Frontend Development",
    emoji: "🥐",
    cookingTime: "4 years",
    difficulty: "Expert",
    description:
      "Delicate frontend creations that delight users with every interaction",
    ingredients: [
      { name: "React", amount: "Expert" },
      { name: "TypeScript", amount: "Advanced" },
      { name: "Next.js", amount: "Advanced" },
      { name: "CSS/SASS", amount: "Expert" },
      { name: "Tailwind", amount: "Advanced" },
      { name: "JavaScript", amount: "Expert" },
    ],
    color: "from-amber-100 to-orange-200",
    borderColor: "border-amber-300",
  },
  {
    id: 2,
    title: "Hearty Bread",
    category: "Backend Development",
    emoji: "🍞",
    cookingTime: "5 years",
    difficulty: "Advanced",
    description:
      "Robust server-side solutions that form the backbone of applications",
    ingredients: [
      { name: "Node.js", amount: "Advanced" },
      { name: "Express", amount: "Advanced" },
      { name: "PostgreSQL", amount: "Intermediate" },
      { name: "MongoDB", amount: "Intermediate" },
      { name: "REST APIs", amount: "Advanced" },
    ],
    color: "from-amber-50 to-yellow-100",
    borderColor: "border-yellow-400",
  },
  {
    id: 3,
    title: "Sweet Treats",
    category: "UI/UX Design",
    emoji: "🍰",
    cookingTime: "2 years",
    difficulty: "Intermediate",
    description: "Beautiful designs that create delightful user experiences",
    ingredients: [
      { name: "Prototyping", amount: "Advanced" },
      { name: "User Research", amount: "Intermediate" },
      { name: "Wireframing", amount: "Advanced" },
      { name: "Color Theory", amount: "Advanced" },
    ],
    color: "from-pink-50 to-rose-100",
    borderColor: "border-pink-300",
  },
  {
    id: 4,
    title: "Fresh Ingredients",
    category: "Programming Languages",
    emoji: "🥬",
    cookingTime: "6 years",
    difficulty: "Expert",
    description:
      "Core programming languages that form the foundation of development",
    ingredients: [
      { name: "JavaScript", amount: "Expert" },
      { name: "TypeScript", amount: "Advanced" },
      { name: "Python", amount: "Advanced" },
      { name: "Java", amount: "Advanced" },
      { name: "Golang", amount: "Intermediate" },
    ],
    color: "from-green-50 to-emerald-100",
    borderColor: "border-green-300",
  },
];
